version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=propvue
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=propvue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432