version: '3'
services:
  master_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=propvue
    ports:
      - '5432:5432'